<template>
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
    <div class="absolute bottom-20 bg-white w-px h-px animate-float rounded-full opacity-0"
        :style="{ left: Math.floor(Math.random() * 98) + '%', animationDelay: Math.floor(Math.random() * 40001) + 'ms', animationDuration: Math.floor(Math.random() * (40000 - 10000 + 1)) + 10000 + 'ms' }" />
</template>